name: 'Increment Version'
description: 'Applying semantic versioning to your repo project'
inputs:
  type-versioning: # id of input
    description: 'Provide a version type: (major, minor, patch)'
    required: true
    default: 'patch'
outputs:
  new-version:
    description: 'Incremented version'
    value: ${{ steps.random-version-generator.outputs.random-version }}
  default-version:
    description: 'Default version'
    value: ${{ steps.versioning-sh.outputs.default_version }}
runs:
  using: 'composite'
  steps:
    - id: random-version-generator
      run: echo "random-version=$(echo "v$RANDOM.0")" >> $GITHUB_OUTPUT
      shell: bash
    - id: action-path
      run: ls -al ${{ github.action_path }}
      shell: bash
    - id: echo_action-path
      run: ${{ github.action_path }}/versioning.sh
      shell: bash
    - id: versioning-sh
      run: echo "default_version=$(echo $DEFAULT_VERSION)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "Goodbye"
      shell: bash
